send letter test
Alena-Ershova/ipr pull request #16
Opened 2022-04-22 08:37 UTC by Alena-Ershova

2022-04-23 15:37 UTC, dKusakin requested changes
- перетащить UI-компоненты в модуль UI, а API-компоненты - в API
- сделать отдельные классы для работы с API почт Mail.ru и Post-Shift
- уйти от статиков в них
- пересмотреть работу в тестах с Cookies и токенами
- почистить код
- чуток прибраться в помниках
- добавить классам и методам JavaDoc комментарии (правило хорошего тона). На геттеры/сеттеры/конструкторы можно забить (возможно, имеет смысл перенести на следующий ПР)

2022-04-23 15:37 UTC, dKusakin commented on iprApi/src/test/java/LettersApiTest.java
>  import pages.MainPage;
Этот и следующий парень ещё тут нужны? Они же к UI относятся.
Вот, кстати, было б правильнее перетащить из утилитарного модуля всё, что с UI связано, в модуль с UI (pages, DrriverWrapper и т.п.), а апишное - в модуль API

2022-04-23 15:37 UTC, dKusakin commented on iprApi/src/test/java/LettersApiTest.java
> +        List<Cookie> cookieList = new LinkedList<>();
Про куки и статики говорили уже, но продублирую:
Лучше сделай работу с апишкой через объект, а этот объект пусть в себе и содержит работу с куками.
В тесте оно тебе, по идее, не надо, да и масштабируемость выйдет на другой уровень

2022-04-23 15:37 UTC, dKusakin commented on iprApi/src/test/java/LettersApiTest.java
>          ValidatableResponse listResponse = given()
Раз Post-Shift оставила, то под работу с его API тоже классец надо замутить

2022-04-23 15:37 UTC, dKusakin commented on iprApi/src/test/java/LettersApiTest.java
> +        sendLetter(letter, token, cookieList);
А ответ на запрос не будем проверять?

2022-04-23 15:37 UTC, dKusakin commented on iprApi/src/test/java/MailRuApiTest.java
> +    private static String token;
И работу с токеном тоже надо бы делегировать.
В принципе, в тестах тебя такие мелочи должны заботить только если ты целенаправленно именно этот функционал проверяешь, в остальном же не будем мы ведь в каждом тесте с ними мыкаться?

2022-04-23 15:37 UTC, dKusakin commented on iprApi/src/test/java/MailRuApiTest.java
>                  .when().log().all().get("/api/v1/k8s/threads/status/smart")
Зачем нам в тестах каждый раз конструировать запросы? Один раз в класс засунула отдельный, да и переиспользуй радостно

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +public class ApiLogin {
Почему именно `ApiLogin`? Куда логин?
Давай переработаем этот класс в "работающий с API почты Mail.ru" и будем через него ходить

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +    public static String login(List<Cookie> cookieList){
Про статики уже поговорили. Не лучшая стратегия

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +    public static String login(List<Cookie> cookieList){
Что-то большеват метод получился, мб его поделить на какие-нибудь приватные?

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +//        cookieList = cookieList.stream().filter(o->!o.getDomain().contains("auth")).collect(Collectors.toList());
Не нужны? Выселить :)

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +                .then().log().all();//.statusCode(302);
А тут чего код не вернула? Там же как раз 302 должен прийти

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +        RestAssured.baseURI = "https://auth.mail.ru";
Ну вот кстати через статику baseURI тоже не самое удачное.
Хз, какой он остался, хотя мб и не выстрелит пока.
Но даже сейчас у тебя есть тесты, которые идут по разным базовым (post-shift и mail) и если где-то ты будеш ожидать, что сие поле в определенном значении, а по факту не так, то прилетит ошибка в рантайме.
В общем, мне видится более правильной стратегия указывать непосредственно в запросе либо свою спеку (`RequestSpecification` кажись), чем полагаться на общедоступную к изменению статику (надо контролировать кто, что поменял. А вернул ли? В общем, больше в голове держать приходится)

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +        RestAssured.baseURI = "https://e.mail.ru";
Мб под эти основные URI завести константы?

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +        updateToken = updateToken.substring(index+begging.length(), updateToken.indexOf("\"", index+begging.length()));
Мб тогда в `index` сразу засунуть `updateToken.indexOf(begging) + begging.length()`
Ну и наверное не `begging`, а `beginning`)

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +                .header("referer", "https://e.mail.ru/inbox/?app_id_mytracker=58519&authid=l2a3clcz.hnc&back=1%2C1&dwhsplit=s10273.b1ss12743s&from=login%2Cnavi&x-login-auth=1")
А точно надо эти Query Parameters указывать? До знака `?` не хватит?

2022-04-23 15:37 UTC, dKusakin commented on iprUtils/src/main/java/apiUtils/ApiLogin.java
> +                .formParam("body", "{\"html\":\"<div>text</div>\",\"text\":\"text\"}")
По-моему, тут должен быть текст отправляемого письма

2022-04-23 15:37 UTC, dKusakin commented on pom.xml
> +            <scope>test,compile</scope>
А есть смысл и `test` и `compile` указывать? Есть ли смысл тут это вообще указывать тогда?

2022-04-23 15:37 UTC, dKusakin commented on pom.xml
> +            <scope>test,compile</scope>
Тот же вопрос, что и повыше

2022-04-23 15:37 UTC, dKusakin commented on pom.xml
>              <groupId>io.rest-assured</groupId>
(к строкам повыше не закомментиться, поэтому тут)
А еще у тебя `junit-jupiter` имеет версию `RELEASE`, которая отличается от остальных
Да и вообще указание версий `RELEASE` и `LATEST` в maven значится как `deprecated`

2022-04-25 08:49 UTC, Alena-Ershova commented on iprApi/src/test/java/MailRuApiTest.java
> +    private static String token;
Не совсем понятно, что имеется в виду. Логин отдельно с ним уже работает.

2022-04-25 14:20 UTC, dKusakin commented on iprApi/src/test/java/MailRuApiTest.java
> +    private static String token;
У тебя токен сидит в *тестах*, а зачем нам в тестах знать о его существовании?
Пусть о нем знает лишь объект специального класса, работающего с апишкой майла

2022-04-26 07:25 UTC, dKusakin requested changes
- доперенести запросы Post-Shift из тестов в созданный класс
- прибрать тесты, использующие Post-Shift
- доработать сохранение и получение кук и токена

2022-04-26 07:25 UTC, dKusakin commented on iprApi/src/main/java/apiUtils/MailRuApiUtils.java
> +        return getToken();
А зачем? Определи этот токен приватным полем в этом классе, да и юзай внутри.
Если какой-нибудь запрос будет пытаться незасеченный использовать, то кидай исключение а-ля "кто-то забыл залогиниться"

2022-04-26 07:25 UTC, dKusakin commented on iprApi/src/main/java/apiUtils/MyCookies.java
> +    private static List<Cookie> cookieList = new LinkedList<>();
Зачем тут статика? Ты хочешь всеми http-клиентами юзать одни и те же куки?
По-моему, логичнее каждому иметь своё хранилище - у одного куки почты, у второго куки какого-нибудь облачного хранилища и т.п.
Ну и да, это опять глобальное состояние, за которым надо следить. Если у тебя один тест затрет что-то из кук, что нужно в другом, то будет вообще невесело

2022-04-26 07:25 UTC, dKusakin commented on iprApi/src/main/java/apiUtils/PostShiftApiUtils.java
> +        RestAssured.baseURI = "https://post-shift.ru";
Глобальный `baseURI`

2022-04-26 07:25 UTC, dKusakin commented on iprApi/src/main/java/apiUtils/PostShiftApiUtils.java
> +    public static String createMail(){
Хоть тут статика особо и не стреляет, но тут тое логичнее было б хранить хэш в каких-нибудь кредах, считывать через конструктор и т.д., а то гвоздями всё прибили.
Хотя логичнее хэш было б в каких-нибудь переменных среды (окружения) хранить и оттуда дергать, но это просто мысли вслух

2022-04-26 07:25 UTC, dKusakin commented on iprApi/src/test/java/LettersApiTest.java
>          ValidatableResponse listResponse = given()
UP
Так и не включила в отдельный класс.
И что-то тут вообще `baseURI` не видно, вот и как и читать, куда этот запрос поехал?

2022-04-26 07:25 UTC, dKusakin commented on iprApi/src/main/java/apiUtils/PostShiftApiUtils.java
> +        return response.extract().response().jsonPath().get("key");
А стоп, всё же роляет. Ключ-то здесь как и токен у майла. Храни его внутри объекта и подпихивай в нужные запросы, зачем он в тесте кому-либо нужен?

2022-04-26 11:09 UTC, dKusakin commented on iprApi/src/main/java/apiUtils/MailRuApiUtils.java
> +                .formParam("from", letter.getAddress())
У тебя параметр `from` и параметр `email` стучатся к одному и тому же полю объекта `letter`.
Так ты только себе сможешь письма отправлять

2022-04-26 12:07 UTC, dKusakin approved these changes

2022-04-26 12:07 UTC, dKusakin commented on iprApi/src/test/java/LettersApiTest.java
> +        Letter letter = new Letter(getLogin("default"), createString(), createString(), null);
`getLogin("default")` указывает же куда отправлять? А чего тогда себе, а не на созданную почту?

2022-04-26 12:07 UTC, dKusakin commented on iprApi/src/main/java/apiUtils/MailRuApiUtils.java
> +                .formParam("email", address)
Здесь тоже "от кого"

2022-04-26 12:08 UTC, merged