реализованы модули для тестов
Alena-Ershova/ipr pull request #6
Opened 2021-12-13 15:35 UTC by Alena-Ershova

2021-12-14 08:12 UTC, dKusakin requested changes
Оставь корневой только для управления общими зависимостями/репозиториями/общими настройками
Сделай модуль с общим утилитарным функционалом

2021-12-14 08:12 UTC, dKusakin commented on iprApi/pom.xml
> +            <artifactId>ipr</artifactId>
По-моему, делать модуль одновременно дочерним и зависимым от одного и того же - не лучшая практика. У тебя в дочернем все равно все зависимости родительского подтягиваются.
А общий утилитарный функционал лучше вынести в отдельный модуль дочерний модуль наряду с созданными тестовыми

2021-12-14 08:12 UTC, dKusakin commented on src/main/java/utils/cipher/EncryptionUtils.java
> +import java.net.URISyntaxException;
Странно, что этот тут затесался, хотя больше ничего не менялось)

2021-12-15 16:05 UTC, Alena-Ershova commented on src/main/java/utils/cipher/EncryptionUtils.java
> +import java.net.URISyntaxException;
это просто были эксперименты, а зависимость осталась %)

2021-12-20 12:18 UTC, merged