отправка письма из бд
Alena-Ershova/ipr pull request #7
Opened 2021-12-22 14:45 UTC by Alena-Ershova

2022-02-01 17:01 UTC, dKusakin requested changes
1. Надо бы убрать работу с консолью, для отладки ещё ничего, а вот в использовании не очень
2. Прибрать закрытие соединения
3. Избавиться от дублирования общей части запросов (возможно, после 1 будет неактуально)

2022-02-01 17:01 UTC, dKusakin commented on iprUtils/src/main/java/dbintegration/DbDataParser.java
> +                connection.close();
Эта штука ругается на null. На самом деле, посмотри на интерфейсы, что реализует `Connection`.
Есть более красивый способ его закрывать, даже в одном из ПРов уже его обсуждали

2022-02-01 17:01 UTC, dKusakin commented on iprUtils/src/main/java/dbintegration/DbDataParser.java
> +            result = secondStatement.executeQuery("SELECT Letter.letter_id, email, content\n" +
По-моему, выше уже используется очень похожая строка. А зачем их полностью дублировать?

2022-02-01 17:01 UTC, dKusakin commented on iprUtils/src/main/java/dbintegration/DbDataParser.java
> +                    "WHERE Letter.letter_id ="+letterId+";");
Можно так параметр задать, а можно ещё через `PreparedStatement`

2022-02-01 17:01 UTC, dKusakin commented on iprUtils/src/main/java/dbintegration/DbDataParser.java
> +            System.out.println("Выберите email и введите его id");
Вот ввод мне тут, честно говоря, не симпатизирует. Получается, что это добро требует слежения за ним, т.е. мы должны сидеть и ждать, когда консоль нас позовет.
Предлагаю так: получить письма запросом, собрать их все в лист и выбрать из него случайный элемент.
Самое интересное тут - собрать. Возможно, тебе поможет метод `ResultSet#getMataData()` (имена колонок и т.п.)

2022-02-01 17:01 UTC, dKusakin commented on iprUtils/src/main/java/wrapper/DriverWrapper.java
> +import org.openqa.selenium.chrome.ChromeDriver;
Артефакт отладки?

2022-02-02 15:44 UTC, Alena-Ershova commented on iprUtils/src/main/java/wrapper/DriverWrapper.java
> +import org.openqa.selenium.chrome.ChromeDriver;
да, у меня сафарька плохо себя вела немного, импорт остался

2022-02-02 17:58 UTC, dKusakin approved these changes

2022-02-02 17:58 UTC, dKusakin commented on iprUtils/src/main/java/dbintegration/DbDataParser.java
> +                    "FROM Contact INNER JOIN Letter_Contact INNER JOIN Letter INNER JOIN content\n" +
Сейчас поглядел и маааленькая ремарка чисто моего восприятия. На мой взгляд, запросы легче читаются когда условия сразу к соединяемым таблицам пишутся, т.е.
```
SELECT *
FROM A a
JOIN B b ON a.idB = b.id
JOIN C c ON b.idC = c.id
```

2022-02-13 11:12 UTC, merged